#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm test || (
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                Unit Test Failed. Make the required changes listed above, add changes and try to fix again.'
        false; 
)

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm lint-staged ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your code looks disgusting. 🤢🤮🤢🤮
            lint Check Failed. Refactor your code again!.';
    false;
)
