#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
pnpm test || (echo "Tests failed! Push aborted." && exit 1)

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm run lint || (echo "Push aborted, please remove comments!" && exit 1)
